image: virtuex/base_java_env:gradle-4.10.2-openjdk-7-openjdk-8-docker-18

stages:
  - build
  - test

before_script:
  - echo "Restoring Packages..."

build_job:
  stage: build
  script:
    - echo "Release build..."
    - gradle build

test_job:
  stage: test
  script:
    - echo "Tests run..."
    # 切换到 JDK8
    - export JAVA_HOME=$JAVA8_HOME
    - export PATH=${JAVA_HOME}/bin:$PATH
    - gradle test
    - gradle jacocoTestReport
    - gradle -b sonarqube.gradle sonarqube -Dsonar.analysis.mode="${MODE}" -Dsonar.gitlab.project_id=$CI_PROJECT_PATH -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME


